window.PAYEEPROOF_MONERIUM_CHAINS = {
  ethereum: {
    label: 'Ethereum',
    apiChain: 'ethereum',
    walletChainIdHex: '0x1',
    walletLabel: 'Ethereum Mainnet',
    sandboxPartnerKey: 'sepolia',
    isSandboxChain: false,
  },
  sepolia: {
    label: 'Ethereum Sepolia',
    apiChain: 'sepolia',
    walletChainIdHex: '0xaa36a7',
    walletLabel: 'Ethereum Sepolia',
    isSandboxChain: true,
  },
  arbitrum: {
    label: 'Arbitrum',
    apiChain: 'arbitrum',
    walletChainIdHex: '0xa4b1',
    walletLabel: 'Arbitrum One',
    sandboxPartnerKey: 'arbitrum sepolia',
    isSandboxChain: false,
  },
  'arbitrum sepolia': {
    label: 'Arbitrum Sepolia',
    apiChain: 'arbitrum sepolia',
    walletChainIdHex: '0x66eee',
    walletLabel: 'Arbitrum Sepolia',
    isSandboxChain: true,
  },
  base: {
    label: 'Base',
    apiChain: 'base',
    walletChainIdHex: '0x2105',
    walletLabel: 'Base',
    sandboxPartnerKey: 'base sepolia',
    isSandboxChain: false,
  },
  'base sepolia': {
    label: 'Base Sepolia',
    apiChain: 'base sepolia',
    walletChainIdHex: '0x14a34',
    walletLabel: 'Base Sepolia',
    isSandboxChain: true,
  },
  polygon: {
    label: 'Polygon',
    apiChain: 'polygon',
    walletChainIdHex: '0x89',
    walletLabel: 'Polygon',
    sandboxPartnerKey: 'amoy',
    isSandboxChain: false,
  },
  amoy: {
    label: 'Polygon Amoy',
    apiChain: 'amoy',
    walletChainIdHex: '0x13882',
    walletLabel: 'Polygon Amoy',
    isSandboxChain: true,
  },
};

window.PAYEEPROOF_MONERIUM_CHAIN_ALIASES = {
  ethereum: 'ethereum',
  sepolia: 'sepolia',
  arbitrum: 'arbitrum',
  'arbitrum sepolia': 'arbitrum sepolia',
  'arbitrum-sepolia': 'arbitrum sepolia',
  arbitrum_sepolia: 'arbitrum sepolia',
  arbitrumsepolia: 'arbitrum sepolia',
  base: 'base',
  'base sepolia': 'base sepolia',
  'base-sepolia': 'base sepolia',
  base_sepolia: 'base sepolia',
  basesepolia: 'base sepolia',
  polygon: 'polygon',
  amoy: 'amoy',
  'polygon amoy': 'amoy',
  'polygon-amoy': 'amoy',
  polygon_amoy: 'amoy',
  polygonamoy: 'amoy',
};
